#配置端口号
server:
  port: 8762

spring:
  #默认使用配置
  datasource:
      url: jdbc:mysql://localhost:3306/db_menu?useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: cn.com.huaruan.model
  mapperLocations: classpath:cn.com.huaruan.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 快递鸟配置信息
kdniao:
  eBusinessId: 1554532
  appKey: dc571760-2bb4-41e4-944d-a5f34c826391
  expressQueryReqUrl: http://api.kdniao.com/Ebusiness/EbusinessOrderHandle.aspx
  expressSubscribeReqUrl: http://api.kdniao.com/api/dist
  subscribeQueryReqUrl: ""