#配置端口号
server:
  port: 8762

spring:
  #默认使用配置
  datasource:
      url: jdbc:mysql://localhost:3306/db_user?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true
      username: root
      password: 123456
      druid:
        initial-size: 5 #连接池初始化大小
        min-idle: 10 #最小空闲连接数
        max-active: 20 #最大连接数
        web-stat-filter:
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
        stat-view-servlet: #访问监控网页的登录用户名和密码
          login-username: druid
          login-password: druid
  ## Elasticsearch配置文件（必须）
  ## 该配置和Elasticsearch的elasticsearch.yml中的配置信息有关
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.153.129:9300
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: cn.com.huaruan.model
  mapperLocations: classpath:cn.com.huaruan.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 快递鸟配置信息
kdniao:
  eBusinessId: 1554532
  appKey: dc571760-2bb4-41e4-944d-a5f34c826391
  expressQueryReqUrl: http://api.kdniao.com/Ebusiness/EbusinessOrderHandle.aspx
  expressSubscribeReqUrl: http://api.kdniao.com/api/dist
  subscribeQueryReqUrl: ""